phpApp:
  name: php-app-deployment
  image: mkhalid77/php-app:latest
  replicas: 1
  service:
    type: NodePort
    port: 80

mysql:
  image: mysql:8.0
  db: "dGVzdGRi"
  user: "bWtoYWxpZA=="
  password: "bWtoYWxpZA=="
  rootUser: "cm9vdA=="
  rootPassword: "cm9vdHBhc3N3b3Jk"
  storage: 3Gi
  storageClass: ebs-sc

# mysql:
#   image: mysql:8.0
#   db: "testdb"
#   user: "mkhalid"
#   password: "mkhalid"
#   rootUser: "root"
#   rootPassword: "rootpassword"
#   storage: 3Gi
#   storageClass: ebs-sc