apiVersion: v1
kind: Service
metadata:
  name: php-app-service
  namespace: {{ .Values.phpApp.namespace }}  
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
