apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: {{ .Values.phpApp.service.port }}
      targetPort: 80
  type: {{ .Values.phpApp.service.type }}
