apiVersion: v1
kind: Secret
metadata:
  name: php-app-secret
type: Opaque
data:
  MYSQL_DB: {{ .Values.mysql.database | b64enc }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASS: {{ .Values.mysql.password | b64enc }}
  MYSQL_ROOT_USER: {{ .Values.mysql.rootUser | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
