apiVersion: v1
kind: Secret
metadata:
  name: php-app-secret
  namespace: {{ .Values.phpApp.namespace }}  
type: Opaque
data:
  MYSQL_HOST: bXktbXlzcWw=               # base64 encoded 'my-mysql'
  MYSQL_USER: bWtoYWxpZA==              # base64 encoded 'mkhalid'
  MYSQL_PASS: bWtoYWxpZA==              # base64 encoded 'mkhalid'
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # base64 encoded 'rootpassword'
  MYSQL_DB: dGVzdGRi                    # base64 encoded 'testdb'
  MYSQL_ROOT_USER: cm9vdA==              # base64 encoded 'root'


