apiVersion: v1
kind: Secret
metadata:
  name: php-app-secret
type: Opaque
data:
  MYSQL_DB: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASS: {{ .Values.mysql.password }}
  MYSQL_ROOT_USER: {{ .Values.mysql.rootUser }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
